routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('properties', 'PropertyController')->except(['show'])->middleware('auth');
Route::get('properties/{slug}', 'PropertyController@show')->name('properties.show')->middleware('auth');

// Static pages
Route::get('/detail', function () {
    return view('detail');
});

Route::get('/developers', function () {
    return view('index-developers');
});

Route::get('/houses', function () {
    return view('index-houses');
});

Route::get('/developers_details', function () {
    return view('developers-details');
});

Route::get('/houses_details', function () {
    return view('houses-details');
});

app/Property.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Property extends Model
{
    protected $fillable = [
      'name',
      'description' ,
      'address',
      'price' ,
      'contact_email',
      'image_name',
      'status'
    ];
    /**
     * Slug attribute
     */
    public function setNameAttribute($name){

      $this->attributes['name'] = $name;
      $this->attributes['slug'] = str_slug($name);
    }
    
    /**
     * Gets date of creation attribute
     * 
     */
    public function getDateCreatedAttribute(){
      
      return $this->created_at->diffForHumans();
    }

    /**
     * Get user for this property
     * 
     */
    public function user(){

      return $this->belongsTo(User::class);
    }

    /**
     * Gets Url attribute
     *
     * @return url
     */
    public function getUrlAttribute()
    {
        return route("properties.show", $this->slug);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PropertyController.php
<?php

namespace App\Http\Controllers;

use App\Property;
use Illuminate\Http\Request;
use App\Http\Requests\PropertyRequest;

class PropertyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Property::latest()->paginate(5);
        return view('property.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $property = new Property();
        // $request->user()->questions()->create($request->only('title', 'body'));

        return view('property.create', compact('property'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PropertyRequest $request)
    {
        Property::create($request->all());

        return redirect()->route('properties.index')->with('success', "Tu propiedad ha sido creada");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Property  $property
     * @return \Illuminate\Http\Response
     */
    public function show(Property $property)
    {
      return view('property.show', compact('property'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Property  $property
     * @return \Illuminate\Http\Response
     */
    public function edit(Property $property)
    {
        return view("property.edit", compact('property'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Property  $property
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Property $property)
    {
        $property->update($request->all());

        return redirect('/properties')->with('success', "Propiedad actualizada");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Property  $property
     * @return \Illuminate\Http\Response
     */
    public function destroy(Property $property)
    {
        $property->delete();

        return redirect('/properties')->with('success', "Propiedad borrada.");
    }
}

resources/views/detail.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Urban - Desarrollo de proyectos urbanísiticos | Home</title>

    <!-- Favicon  -->
    <link rel="icon" href="img/core-img/favicon.ico">

    <!-- Style CSS -->
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

</head>

<body>
  <div id="app">
    <example-component></example-component>
  </div>

    <!-- Preloader -->
    <div id="preloader">
        <div class="south-load"></div>
    </div>

<section class="detail-page">
  <div class="row">
    <div class="col-md-6">
      <div class="dept-name">
        <h2>Departamento Maipu 470</h2>
      </div>
    </div>
    <div class="col-md-6">
      <div class="dept-price">
        <h2 class="status">Venta</h2>
        <h2 class="price">USD <b>280.000</b></h2>
      </div>    
    </div>
    <div class="col-md-6">
      <div class="dept-slider">
        <img src="img/bg-img/feature1.jpg" alt="">
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-12">
          <div class="dept-details">
            <div class="detail-box">
              <img src="img/icons/superficie.svg" alt="">
              <p>Superficie</p>
              <h4>90m<sup>2</sup></h4>
            </div>
            <div class="detail-box">
              <img src="img/icons/cama.svg" alt="">
              <p>Dormitorios</p>
              <h4>3</h4>
            </div>
            <div class="detail-box">
              <img src="img/icons/ducha.svg" alt="">
              <p>Baños</p>
              <h4>2</h4>
            </div>
            <div class="detail-box">
              <img src="img/icons/auto.svg" alt="">
              <p>Cochera</p>
              <h4>1</h4>
            </div>
            <div class="detail-box">
              <img src="img/icons/pileta.svg" alt="">
              <p>Amenities</p>
              <h4>Si</h4>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div class="dept-contact">
            <form>
              <h3 class="contact-title">Contacto:</h3>
              <h3 class="contact-title-2">+549 11 53294260</h3>
              <div class="contact-info">
                <div class="contact-info-item">
                  <input type="text" placeholder="Nombre:">
                  <p class="contact-sub-info"></p>
                </div>
                <div class="contact-info-item">
                  <input type="text" placeholder="Teléfono:">
                  <p class="contact-sub-info"></p>
                </div>
                <div class="contact-info-item">
                  <input type="email" placeholder="Email:">
                  <p class="contact-sub-info"></p>
                </div>
                <div class="contact-info-item">
                  <textarea name="Mensaje" id="" cols="30" rows="10" placeholder="Mensaje:"></textarea>
                  <p class="contact-sub-info"></p>
                </div>
              </div>
            </form>  
          </div>
          <div class="btn contact-send">
            <a href="#">Enviar</a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="dept-description">
        <div class="description-top">
          <h3 class="desc-title">Descripción</h3>
        </div>
        <div class="description-bot">
          <h5 class="description-header">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed bibendum ex ac neque iaculis. 
          </h5>
          <p class="description-body">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam mi nulla, egestas id dolor a, tempus malesuada magna. Vestibulum congue rhoncus odio sit amet finibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed et sem ut odio placerat feugiat. Quisque interdum nunc sed cursus lobortis. Sed accumsan augue ut pharetra consectetur. Etiam lacinia augue vel purus tristique aliquet. Morbi venenatis magna ac nulla congue ornare. Nunc vel tortor sed tellus cursus luctus. Suspendisse potenti. Cras id venenatis libero. 
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="dept-map">
        <div class="map-top">
          <h3 class="map-title">Ubicación / Mapa</h3>
          <div class="map-socialmedia">
            <a href="#" target="_blank"><img src="img/icons/whatsapp.svg" alt="Whatsapp"></a>
            <a href="#" target="_blank"><img src="img/icons/facebook.svg" alt="Facebook"></a>
            <a href="#" target="_blank"><img src="img/icons/instagram.svg" alt="Instagram"></a>
          </div>
        </div>
        <div class="map-bot">
          <div class="map-responsive">
          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6959.996374489853!2d-58.405724992216996!3d-34.58694057808897!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcca83d2aa1521%3A0xc7a941fe0d021ba0!2sAlto+Palermo+Shopping!5e0!3m2!1ses!2sar!4v1557097984857!5m2!1ses!2sar" width="522" height="390" frameborder="0" style="border:0" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="dept-info">
        <h4 class="dept-title">Información Básica:</h4>
        <ul>
          <li>
            <p>Ambientes:</p><span>2</span>
          </li>
          <li>
            <p>Dormitorios:</p><span>1</span>
          </li>
          <li>
            <p>Baños:</p><span>1</span>
          </li>
          <li>
            <p>Toilettes:</p><span>0</span>
          </li>
          <li>
            <p>Antigüedad:</p><span>50</span>
          </li>
          <li>
            <p>Expensas:</p><span>3700</span>
          </li>
          <li>
            <p>Orientación:</p><span>Suroeste</span>
          </li>
          <li>
            <p>Disposición:</p><span>Frente</span>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div class="dept-superficies">
        <h4 class="dept-title">Superficies:</h4>
        <ul>
          <li>
            <p>Cubierta:</p><span>74.30 m<sup>2</sup></span>
          </li>
          <li>
            <p>Semicubierta:</p><span>3.50 m<sup>2</sup></span>
          </li>
          <li>
            <p>Total Construido:</p><span>77.80 m<sup>2</sup></span>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div class="dept-adicionales">
        <h4 class="dept-title">Adicionales:</h4>
        <ul>
          <li>
            <p>Aire Aconcicionado:</p><span>Individual</span>
          </li>
          <li>
            <p>Agua Caliente:</p><span>Individual</span>
          </li>
          <li>
            <p>Calefacción:</p><span>Por Aire</span>
          </li>
          <li>
            <p>Luminoso</p>
          </li>
          <li>
            <p>Antigüedad:</p><span>50</span>
          </li>
          <li>
            <p>Expensas:</p><span>3700</span>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div class="dept-ambientes">
        <h4 class="dept-title">Ambientes:</h4>
        <ul>
          <li>
            <p>Cocina</p>
          </li>
          <li>
            <p>Living Comedor</p>
          </li>
          <li>
            <p>Hall</p>
          </li>
          <li>
            <p>Escritorio</p>
          </li>
          <li>
            <p>Lavadero</p>
          </li>
          <li>
            <p>Dependencia</p>
          </li>
          <li>
            <p>Entrada Servicio</p>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="js/plugins.js"></script>
    <script src="js/classy-nav.min.js"></script>
    <script src="js/jquery-ui.min.js"></script>
    <!-- Active js -->
    <script src="js/active.js"></script>
    <!-- <script src="/js/app.js"></script>  -->
</body>

</html>

resources/views/developers-details.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Urban - Desarrollo de proyectos urbanísiticos | Home</title>

    <!-- Favicon  -->
    <link rel="icon" href="img/core-img/favicon.ico">

    <!-- Style CSS -->
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

</head>

<body>
  <div id="app">
    <example-component></example-component>
  </div>

    <!-- Preloader -->
    <div id="preloader">
        <div class="south-load"></div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">

        <!-- Top Header Area -->
        <!-- <div class="top-header-area">
            <div class="h-100 d-md-flex justify-content-between align-items-center">
                <div class="email-address">
                    <a href="mailto:contact@southtemplate.com">contact@southtemplate.com</a>
                </div>
                <div class="phone-number d-flex">
                    <div class="icon">
                        <img src="img/icons/phone-call.png" alt="">
                    </div>
                    <div class="number">
                        <a href="tel:+45 677 8993000 223">+45 677 8993000 223</a>
                    </div>
                </div>
            </div>
        </div> -->

        <!-- Main Header Area -->
        <div class="main-header-area" id="stickyHeader">
          <div class="classy-nav-container breakpoint-off">
            <!-- Classy Menu -->
            <div class="head-title">Arquitectura</div>
            <nav class="classy-navbar justify-content-between" id="southNav">

                    <!-- Logo -->
                    <a class="nav-brand" href="index.html"><img src="img/core-img/logo-developers.png" alt=""></a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- close btn -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">
                            <ul>
                                <li><a href="#">Home</a></li>
                            </ul>

                            <!-- Search Form -->
                            <div class="south-search-form">
                                <form action="#" method="post">
                                    <input type="search" name="search" id="search" placeholder="Busca por nombre o dirección ...">
                                    <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                                </form>
                            </div>

                            <!-- Search Button -->
                            <!-- <a href="#" class="searchbtn"><i class="fa" aria-hidden="true"></i></a> -->
                        </div>
                        <!-- Nav End -->
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->

    <!-- ##### Content Area Start ##### -->

    <section>
        <div class="row details-view">
            <div class="col-md-7">
                <img src="img/bg-img/feature1.jpg" alt="">
            </div>
            <div class="col-md-5">
                <div class="details-info">
                    <div class="details-name">
                        <h6>Proyecto</h6>
                        <h3>Torre quesevendarapido</h3>
                    </div>
                    <div class="details-place">
                        <h6>Ubicación</h6>
                        <h3>Palermo, Argentina</h3>
                    </div>
                    <div class="details-year">
                        <h6>Año</h6>
                        <h3>2017</h3>
                    </div>
                    <div class="details-description">
                        <h6>Descripción</h6>
                        <p>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non mauris leo. Cras maximus efficitur purus, ac ultrices leo vulputate in. Nam quis ullamcorper enim. Sed feugiat lacus dui, at molestie massa tempor ut. Praesent vehicula nisi ac vestibulum scelerisque. Duis venenatis quam sit amet magna lobortis sollicitudin. Vestibulum molestie mauris at ipsum ultrices, et mattis ante fringilla. Aliquam at suscipit nunc, eu rutrum felis. Morbi accumsan posuere tristique. Donec at nibh ut arcu finibus pretium. Nunc eu est id justo consectetur consectetur suscipit vitae lorem. Vivamus vulputate venenatis ornare.

Donec ac efficitur ligula. Aliquam tincidunt a orci a vestibulum. Ut tristique erat nec libero lobortis, varius rhoncus neque pharetra. Praesent convallis, enim tristique tincidunt cursus, justo sem vehicula lacus, ut eleifend nisl dolor in lectus. Maecenas et justo id neque faucibus commodo. Sed odio massa, tincidunt at euismod sit amet, tristique non nisi. Sed risus nibh, laoreet vitae purus id, sollicitudin ornare justo. Sed ornare elementum augue, lacinia varius mauris gravida nec. Nulla egestas sagittis erat. Aliquam quis orci rhoncus, porta urna quis, posuere orci. Integer posuere lorem et augue elementum, vitae varius sapien tristique. Donec viverra rutrum ex sed viverra.

Cras eget tincidunt massa.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="js/plugins.js"></script>
    <script src="js/classy-nav.min.js"></script>
    <script src="js/jquery-ui.min.js"></script>
    <!-- Active js -->
    <script src="js/active.js"></script>
    <!-- <script src="/js/app.js"></script>  -->
</body>

</html>

resources/views/home.blade.php
@extends('layouts.dashboard')

@section('content')



@endsection

resources/views/layouts/_messages.blade.php
@if (session('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success!</strong> {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/partials/side-menu.blade.php
<div class="container home-side">
    <div class="row">
        <div class="col-md-3 section-l">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link active" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Propiedades</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Nosotros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Inversiones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Crédito</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Tasaciones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contacto</a>
                </li>
              </ul>
        </div>
        <div class="col-md-9 section-r">
            
        </div>
    </div>
</div>

@push('styles')
    <link rel="stylesheet" href="{{ asset('css/side-styles.css') }}">
@endpush

resources/views/property/create.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header create-header">
                    <div class="d-flex align-items-center">
                        <h2>Crear propiedad</h2>
                        <div class="ml-auto">
                            <a href="{{ route('properties.index') }}" class="btn btn-outline-secondary">Mostrar todas las propiedades</a>
                        </div>
                    </div>
                    
                </div>

                <div class="card-body">
                   <form action="{{ route('properties.store') }}" method="post">
                        @include ("property._form", ['buttonText' => "Crear propiedad"])
                   </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/property/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
              <div class="container property-cont">
                <img class="card-img-top" src="https://picsum.photos/id/743/1000/350" alt="Card image cap">
                <div class="ml-auto">
                      <!-- Button trigger modal -->
                      <div class="ml-auto">
                        <a href="#" class="btn btn-outline-secondary" data-toggle="modal" data-target="#exampleModalLong">Cargar imágenes</a>
                      </div>
                    </div>
                  </div>
              </div>
                <div class="card-header">
                  <div class="d-flex align-items-center">
                    <h2> Editar Propiedad </h2>
                    <div class="ml-auto">
                      <a href="{{ route('properties.index') }}" class="btn btn-outline-secondary">Volver</a>
                    </div>
                  </div>
                </div>

                <div class="card-body">
                <form action="{{ route('properties.update', $property->id) }}" method="post">
                  {{ method_field('PUT') }}
                  @include('property._form', ['buttonText'=> 'Guardar'])
                </form>
                </div>
            </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Carga hasta 5 imágenes</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <image-uploader-component></image-uploader-component>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary">Guardar</button>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
@endsection

resources/views/property/index.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="container prop-container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h2>Propiedades</h2>
                        <div class="ml-auto">
                            <a href="{{ route('properties.create') }}" class="btn btn-verde">Crear propiedad</a>
                        </div>
                    </div>
                    
                </div>

                <div class="card-body">
                    @include ('layouts._messages')
                    @foreach ($items as $item)
                        <div class="media">
                            <div class="d-flex flex-column counters">
                                <img class="card-img-top" src="https://picsum.photos/id/743/200/120" alt="Card image cap">
                            </div>
                            <div class="media-body">
                                <div class="d-flex align-items-center">
                                    <h3 class="mt-0"><a href="{{ $item->url }}">{{ $item->name }}</a></h3>
                                    <div class="ml-auto">
                                        {{-- @can ('update', $item) --}}
                                            <a href="{{ route('properties.edit', $item->id) }}" class="btn btn-verde">Editar</a>
                                        {{-- @endcan
                                        @can ('delete', $item) --}}
                                            <form class="form-delete" method="post" action="{{ route('properties.destroy', $item->id) }}">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-gris" onclick="return confirm('Estás seguro?')">Eliminar</button>
                                            </form>
                                        {{-- @endcan --}}
                                    </div>
                                </div>
                                {{-- <p class="lead">
                                    Asked by 
                                    <a href="{{ $item->user->url }}">{{ $item->user->name }}</a> 
                                    <small class="text-muted">{{ $item->created_date }}</small>
                                </p> --}}
                                {{ str_limit($item->description, 250) }}
                            </div>                        
                        </div>
                        <hr>
                    @endforeach

                    <div class="mx-auto">
                        {{ $items->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection